on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    types: [ opened, labeled, synchronize ]

name: PHPUnit
jobs:
  build-test:
    if: contains(github.event.pull_request.labels.*.name, 'run tests')
    runs-on: ubuntu-latest
    env:
      WP_MULTISITE: ${{ matrix.multisite }}
    strategy:
      matrix:
        include:
          - php: 7.4
            wordpress: 6.3.2
            pro: current
            lite: master
            multisite: 1
          - php: 8.0.22
            wordpress: 6.3.2
            pro: current
            lite: master
            multisite: 0
    name: ${{ matrix.pro }} with ${{ matrix.lite }} on PHP ${{ matrix.php }} and WP ${{ matrix.wordpress }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - uses: actions/checkout@v4.1.1

      - uses: shivammathur/setup-php@2.30.2
        with:
          php-version: ${{ matrix.php }}
          tools: phpunit-polyfills

      - name: Creating database
        run: |
          sudo /etc/init.d/mysql start
          mysql -u root -proot -e "CREATE DATABASE wordpress_tests;"

      - name: Installing WordPress
        run: |
          export WP_DEVELOP_DIR=/tmp/wordpress/
          git clone --depth=1 --branch="${{ matrix.wordpress }}" https://github.com/WordPress/wordpress-develop.git /tmp/wordpress
          git clone --depth=1 --branch="${{ matrix.lite }}" https://github.com/Strategy11/formidable-forms.git /tmp/wordpress/src/wp-content/plugins/formidable
          cd ..
          cp -r "${GITHUB_REPOSITORY#*/}" "/tmp/wordpress/src/wp-content/plugins/${GITHUB_REPOSITORY#*/}"
          cd "/tmp/wordpress/src/wp-content/plugins/${GITHUB_REPOSITORY#*/}"
          if [[ ${{ matrix.pro }} != "current" ]]; then git checkout ${{ matrix.pro }}; fi
          cd /tmp/wordpress/
          pwd
          cp wp-tests-config-sample.php wp-tests-config.php
          sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
          sed -i "s/yourusernamehere/root/" wp-tests-config.php
          sed -i "s/yourpasswordhere/root/" wp-tests-config.php

      - name: PhpUnit tests
        run: |
          cd "/tmp/wordpress/src/wp-content/plugins/${GITHUB_REPOSITORY#*/}"
          pwd
          phpunit --coverage-clover=coverage.xml
      - name: Send code coverage report to Codecov.io
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: /tmp/wordpress/src/wp-content/plugins/formidable-pro/coverage.xml
