on:
  # Trigger the workflow on pull request,
  pull_request:
    types: [ opened, labeled, synchronize ]

name: Typo Checks
jobs:
  run:
    if: contains(github.event.pull_request.labels.*.name, 'run analysis')
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v4

    - name: Check spelling of file.txt
      uses: crate-ci/typos@master
